FSM:
  Passive:
    mode: [ # motor mode
      10,10,10,10,10,10,
      10,10,10,10,
      1,1,
      1,1,1,1,
      1,1,1,1
    ]
    kd: [
      5,5,6,5,5,6,
      5,5,5,
      0, # reserved
      2,2,
      2,2,2,2,
      2,2,2,2, 
    ]
  FixStand:
    kp: [
      200, 200, 300, 200, 200, 300,
      200, 200, 200, 
      0, # reserved
      40, 40,
      100, 50, 50, 50,
      100, 50, 50, 50,
    ]
    kd: [
      5,5,6,5,5,6,
      5,5,5,
      0, # reserved
      2,2,
      2,2,2,2,
      2,2,2,2,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ 0, -0.28, 0.79, 0, -0.28, 0.79,
        0, 0, 0,
        0, # reserved
        -0.52, -0.52, 
        0.2, 0, 0, 0.32,
        0.2, 0, 0, 0.32,
      ]
    ]
  Velocity:
    policy_dir: ../../../logs/rsl_rl/xhumanoid_lite0430_velocity